import {
	type buildWpOptionStorageArtifacts,
	type RestControllerRouteOptionHandlers,
	type buildWpTaxonomyHelperArtifacts,
	type RestControllerRouteHandlers,
	type TransientStorageArtifacts,
	type WpPostRouteBundle,
	type BlockRenderStub,
	type buildPluginLoaderProgram,
} from '@wpkernel/wp-json-ast';
import { type RESOURCE_STORAGE_HELPERS_SYMBOL } from './storage.artifacts';
import type { IRResource, IRv1 } from '../../ir';
import type {
	IRUiMenuConfig,
	IRUiResourceDescriptor,
} from '../../ir/publicTypes';
import { type WP_POST_ROUTE_HELPER_SYMBOL } from './controller.wpPostRoutes';
import type { PhpDriverConfigurationOptions } from '@wpkernel/php-json-ast';
import type { BuilderApplyOptions, BuilderOutput } from '../../runtime/types';
import type {
	ProcessedBlockManifest,
	BlockManifestEntry,
} from '../shared.blocks.manifest';
import type { Workspace } from '../../workspace';
import { type GeneratePhaseInput } from './entry.plugin';

/**
 * Represents the artifacts generated by the WP Option storage helper.
 *
 * @category AST Builders
 */

export interface WpOptionStorageHelperArtifacts {
	/** The helper methods generated for WP Option storage. */
	readonly helperMethods: ReturnType<
		typeof buildWpOptionStorageArtifacts
	>['helperMethods'];
	/** The route handlers generated for WP Option storage. */
	readonly routeHandlers: RestControllerRouteOptionHandlers;
}
/**
 * Represents the artifacts generated by the WP Taxonomy storage helper.
 *
 * @category AST Builders
 */

export interface WpTaxonomyStorageHelperArtifacts {
	/** The helper methods generated for WP Taxonomy storage. */
	readonly helperMethods: ReturnType<
		typeof buildWpTaxonomyHelperArtifacts
	>['helperMethods'];
	/** The helper signatures generated for WP Taxonomy storage. */
	readonly helperSignatures: ReturnType<
		typeof buildWpTaxonomyHelperArtifacts
	>['helperSignatures'];
	/** The route handlers generated for WP Taxonomy storage. */
	readonly routeHandlers: RestControllerRouteHandlers;
}
/**
 * Represents the state managed by the resource storage helpers.
 *
 * This state stores the generated artifacts for different storage modes
 * (transient, wp-option, wp-taxonomy) keyed by resource name.
 *
 * @category AST Builders
 */

export interface ResourceStorageHelperState {
	/** A map of resource names to their transient storage artifacts. */
	readonly transient: Map<string, TransientStorageArtifacts>;
	/** A map of resource names to their WP Option storage artifacts. */
	readonly wpOption: Map<string, WpOptionStorageHelperArtifacts>;
	/** A map of resource names to their WP Taxonomy storage artifacts. */
	readonly wpTaxonomy: Map<string, WpTaxonomyStorageHelperArtifacts>;
}
export interface ResourceStorageHelperHost {
	[RESOURCE_STORAGE_HELPERS_SYMBOL]?: ResourceStorageHelperState;
}
/**
 * WordPress Options storage configuration type.
 *
 * Represents a resource storage configuration that uses WordPress's `wp_options`
 * table for persistence. Extracted from the IR resource storage union type.
 *
 * @category AST Builders
 */

export type WpOptionStorage = Extract<
	NonNullable<IRResource['storage']>,
	{ mode: 'wp-option' }
>;
/**
 * Represents the state managed by the WP Post route helper.
 *
 * This state stores bundles of generated artifacts for WP Post-based routes,
 * keyed by resource name.
 *
 * @category AST Builders
 */

export interface WpPostRouteHelperState {
	/** A map of resource names to their WP Post route bundles. */
	readonly bundles: Map<string, WpPostRouteBundle>;
}
export interface WpPostRouteHelperHost {
	[WP_POST_ROUTE_HELPER_SYMBOL]?: WpPostRouteHelperState;
}
export interface PopulateWpPostRouteBundlesOptions {
	readonly ir: IRv1;
	readonly state: WpPostRouteHelperState;
}
export type NormalizedMenuConfig = IRUiMenuConfig;
export type PluginLoaderUiResourceDescriptor = IRUiResourceDescriptor;
export interface PluginLoaderUiConfig {
	readonly handle: string;
	readonly assetPath: string;
	readonly scriptPath: string;
	readonly localizationObject: string;
	readonly namespace: string;
	readonly resources: readonly PluginLoaderUiResourceDescriptor[];
}
export interface PopulateArtifactsBaseOptions {
	readonly ir: IRv1;
	readonly state: ResourceStorageHelperState;
}
/**
 * Configuration options for creating the PHP builder.
 *
 * @category AST Builders
 */

export interface CreatePhpBuilderOptions {
	/**
	 * Optional configuration options for the PHP driver.
	 */
	readonly driver?: PhpDriverConfigurationOptions;
}
export type PhpBuilderApplyOptions = BuilderApplyOptions;
/**
 * Options for collating PHP block artifacts during build.
 *
 * @category AST Builders
 */

export interface CollatePhpBlockArtifactsOptions {
	readonly processedBlocks: readonly ProcessedBlockManifest[];
	readonly reporter: BuilderApplyOptions['reporter'];
	readonly suppressWarnings?: boolean;
}
/**
 * Collated WordPress block artifacts for PHP generation.
 *
 * Contains block manifest entries and PHP render callback stubs extracted
 * from processed block definitions.
 *
 * @category AST Builders
 */

export interface CollatedPhpBlockArtifacts {
	readonly manifestEntries: Record<string, BlockManifestEntry>;
	readonly renderStubs: readonly NonNullable<
		ProcessedBlockManifest['renderStub']
	>[];
}
/**
 * Options for staging block render callback stubs to workspace.
 *
 * @category AST Builders
 */

export interface StageRenderStubsOptions {
	readonly stubs: readonly BlockRenderStub[];
	readonly workspace: Workspace;
	readonly output: BuilderOutput;
	readonly reporter: BuilderApplyOptions['reporter'];
}
export type ContentModel = Parameters<
	typeof buildPluginLoaderProgram
>[0]['contentModel'];
export type Resource = GeneratePhaseInput['ir']['resources'][number];
export type PostTypesMap = Map<
	string,
	{
		labels: Record<string, string>;
		supports?: readonly string[];
		taxonomies: Set<string>;
		showUi: boolean;
		showInMenu: boolean;
	}
>;
export type TaxonomiesMap = Map<
	string,
	{
		objectTypes: Set<string>;
		hierarchical?: boolean;
		labels: Record<string, string>;
		showUi: boolean;
		showAdminColumn: boolean;
	}
>;
export type StatusesMap = Map<
	string,
	{
		label: string;
		public?: boolean;
		showInAdminAllList?: boolean;
		showInAdminStatusList?: boolean;
	}
>;
export type WpPostStorage = Extract<
	NonNullable<Resource['storage']>,
	{ mode: 'wp-post' }
>;
export type WpTaxonomyStorage = Extract<
	NonNullable<Resource['storage']>,
	{ mode: 'wp-taxonomy' }
>;
