<?php

declare(strict_types=1);
namespace Test\Namespace\Rest;

/**
 * WPKernel extension shim.
 * Edits to this file will be preserved during apply operations.
 */
if (!class_exists(Test\Namespace\Generated\Rest\FirstController::class)) {
    require_once(__DIR__ . '/../../.wpk/generate/php/Rest/FirstController.php');
}
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → resources.first
 * Schema: auto:first (auto)
 */
class FirstController extends Test\Namespace\Generated\Rest\FirstController
{
}
