<?php

declare(strict_types=1);
namespace Test\Namespace\Rest;

/**
 * WPKernel extension shim.
 * Edits to this file will be preserved during apply operations.
 */
if (!class_exists(Test\Namespace\Generated\Rest\JobController::class)) {
    require_once(__DIR__ . '/../../.wpk/generate/php/Rest/JobController.php');
}
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → resources.job
 * Schema: auto:job (auto)
 */
class JobController extends Test\Namespace\Generated\Rest\JobController
{
}
