<?php

declare(strict_types=1);
namespace Test\Namespace\Rest;

/**
 * WPKernel extension shim.
 * Edits to this file will be preserved during apply operations.
 */
if (!class_exists(Test\Namespace\Generated\Rest\SecondController::class)) {
    require_once(__DIR__ . '/../../.wpk/generate/php/Rest/SecondController.php');
}
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Source: wpk.config.ts → resources.second
 * Schema: auto:second (auto)
 */
class SecondController extends Test\Namespace\Generated\Rest\SecondController
{
}
