<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → php/index
 */
namespace Test\Namespace\Generated;

// WPK:BEGIN AUTO
return ['Test\Namespace\Generated\Rest\BaseController' => __DIR__ . '/Rest/BaseController.php', 'Test\Namespace\Generated\Capability\Capability' => __DIR__ . '/Capability/Capability.php', 'Test\Namespace\Generated\Registration\PersistenceRegistry' => __DIR__ . '/Registration/PersistenceRegistry.php', 'Test\Namespace\Generated\Rest\TodoController' => __DIR__ . '/Rest/TodoController.php'];
// WPK:END AUTO
