import {
	createPhpProgramBuilder,
	type BuilderInput,
	type BuilderOutput,
	type BuilderWriteAction,
	type PipelineContext,
} from '../programBuilder';
import { getPhpBuilderChannel } from '../builderChannel';
import {
	createTestPipelineContext,
	resetTestChannels,
} from './testUtils.test-support';
import { loadDefaultLayout } from '@wpkernel/test-utils/layout.test-support';

describe('pipeline smoke test', () => {
	interface SmokeContext extends PipelineContext {
		readonly builderTag: string;
	}

	interface SmokeInput extends BuilderInput {
		readonly options: BuilderInput['options'] & { readonly slug: string };
	}

	interface SmokeOutput extends BuilderOutput {
		readonly actions: BuilderWriteAction[];
	}

	it('queues program actions and forwards them to the builder output', async () => {
		const baseContext = createTestPipelineContext();
		const context: SmokeContext = {
			...baseContext,
			builderTag: 'cli-smoke',
		};

		const input: SmokeInput = {
			phase: 'generate',
			options: { slug: 'demo-plugin' },
			ir: null,
		};

		const actions: BuilderWriteAction[] = [];
		const output: SmokeOutput = {
			actions,
			queueWrite: jest.fn((action: BuilderWriteAction) => {
				actions.push(action);
			}),
		};

		const layout = loadDefaultLayout();
		const phpFile = `${context.workspace.resolve(layout.resolve('php.generated'))}/Smoke.php`;

		resetTestChannels(context);

		const helper = createPhpProgramBuilder<
			SmokeContext,
			SmokeInput,
			SmokeOutput
		>({
			key: 'pipeline-smoke',
			filePath: phpFile,
			namespace: 'Demo\\Smoke',
			metadata: { kind: 'index-file' },
			build: (builder) => {
				builder.appendDocblock(`Generated by ${context.builderTag}`);
				builder.appendStatement('// pipeline smoke test');
			},
		});

		await helper.apply({
			context,
			input,
			output,
			reporter: context.reporter,
		});

		const queued = getPhpBuilderChannel(context).drain();
		expect(queued).toHaveLength(1);

		const [action] = queued;
		expect(action?.file).toBe(phpFile);
		expect(action?.docblock).toContain('Generated by cli-smoke');
		expect(action?.statements).toContain('// pipeline smoke test');

		for (const queuedAction of queued) {
			output.queueWrite({
				file: queuedAction.file,
				contents: JSON.stringify(queuedAction.program),
			});
		}

		expect(output.queueWrite).toHaveBeenCalledTimes(1);
		expect(actions).toHaveLength(1);
		expect(actions[0]).toMatchObject({
			file: phpFile,
		});
	});
});
