import {
	buildArg,
	buildBooleanNot,
	buildComment,
	buildDeclare,
	buildDeclareItem,
	buildDocComment,
	buildExpressionStatement,
	buildFuncCall,
	buildIfStatement,
	buildName,
	buildScalarInt,
	buildScalarString,
	buildStmtNop,
	type PhpStmt,
} from '@wpkernel/php-json-ast';
import { AUTO_GUARD_BEGIN, AUTO_GUARD_END } from '../constants';
import type { PluginLoaderProgramConfig } from './types';

export function buildPluginHeaderStatement(
	config: PluginLoaderProgramConfig
): PhpStmt {
	const { plugin } = config;
	const packageName = config.namespace.replace(/\\/g, '');
	const lines: string[] = [
		`Plugin Name: ${plugin.name}`,
		`Description: ${plugin.description}`,
		`Version: ${plugin.version}`,
		`Requires at least: ${plugin.requiresAtLeast}`,
		`Requires PHP: ${plugin.requiresPhp}`,
		`Text Domain: ${plugin.textDomain}`,
		`Author: ${plugin.author}`,
	];

	if (plugin.authorUri) {
		lines.push(`Author URI: ${plugin.authorUri}`);
	}

	if (plugin.pluginUri) {
		lines.push(`Plugin URI: ${plugin.pluginUri}`);
	}

	lines.push(`License: ${plugin.license}`);

	if (plugin.licenseUri) {
		lines.push(`License URI: ${plugin.licenseUri}`);
	}

	lines.push(
		'Generated by WPKernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.',
		`Source: ${config.origin} → plugin/loader`,
		`@package ${packageName}`
	);

	return buildStmtNop({
		comments: [buildDocComment(lines)],
	});
}

export function buildStrictTypesDeclare(): PhpStmt {
	return buildDeclare([buildDeclareItem('strict_types', buildScalarInt(1))]);
}

export function buildGuardMarkers(): { begin: PhpStmt; end: PhpStmt } {
	return {
		begin: buildStmtNop({
			comments: [buildComment(`// ${AUTO_GUARD_BEGIN}`)],
		}),
		end: buildStmtNop({ comments: [buildComment(`// ${AUTO_GUARD_END}`)] }),
	};
}

export function buildAccessGuardStatement(): PhpStmt {
	const definedCall = buildFuncCall(buildName(['defined']), [
		buildArg(buildScalarString('ABSPATH')),
	]);
	const guardCondition = buildBooleanNot(definedCall);
	const exitCall = buildFuncCall(buildName(['exit']));

	return buildIfStatement(guardCondition, [
		buildExpressionStatement(exitCall),
	]);
}
