<?php

/**
 * Plugin Name: Test Namespace
 * Description: Bootstrap loader for the Test Namespace WPKernel integration.
 * Version: 0.1.0
 * Requires at least: 6.7
 * Requires PHP: 8.1
 * Text Domain: test-namespace
 * Author: WPKernel Contributors
 * License: GPL-2.0-or-later
 * Generated by WPKernel CLI - edits between WPK:BEGIN AUTO and WPK:END AUTO are managed by the generator.
 * Source: wpk.config.ts → plugin/loader
 * @package TestNamespace
 */
declare(strict_types=1);
namespace Test\Namespace;

/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → plugin/loader
 */
// WPK:BEGIN AUTO
if (!defined('ABSPATH')) {
    exit();
}
/**
 * Retrieve WPKernel REST controllers generated for this plugin.
 * @return array<int, object>
 */
function get_wpkernel_controllers(): array
{
    $classmapPath = plugin_dir_path(__FILE__) . '.wpk/generate/php/index.php';
    if (file_exists($classmapPath)) {
        $classmap = require($classmapPath);
        if (is_array($classmap)) {
            foreach ($classmap as $class => $path) {
                if (!class_exists($class) && file_exists($path)) {
                    require_once($path);
                }
            }
        }
    }
    return [new \Test\Namespace\Generated\Rest\FirstController(), new \Test\Namespace\Generated\Rest\SecondController()];
}
/** Register WPKernel REST controllers with WordPress. */
function register_wpkernel_routes(): void
{
    $controllers = get_wpkernel_controllers();
    foreach ($controllers as $controller) {
        if (!method_exists($controller, 'register_routes')) {
            continue;
        }
        $controller->register_routes();
    }
}
/** Attach wpk hooks required for REST registration. */
function bootstrap_wpk(): void
{
    add_action('rest_api_init', __NAMESPACE__ . '\register_wpkernel_routes');
}
bootstrap_wpk();
// WPK:END AUTO
// Custom plugin logic may be added below. This area is left untouched by the generator.
