<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources (storage + identity metadata)
 */
namespace Test\Namespace\Generated\Registration;

// WPK:BEGIN AUTO
final class PersistenceRegistry
{
    public static function get_config(): array
    {
        return ['resources' => []];
    }
}
// WPK:END AUTO
