import path from 'node:path';
import {
	type RegistrarModuleFactoryOptions,
	type RegistrarModuleMetadata,
} from './types';

/**
 * Builds metadata describing the auto-register module emitted for JS-only blocks.
 *
 * @param    root0
 * @param    root0.outputDir
 * @param    root0.source
 * @category Builders
 */
export function buildAutoRegisterModuleMetadata({
	outputDir,
	source,
}: RegistrarModuleFactoryOptions): RegistrarModuleMetadata {
	const bannerSource = source ?? 'project config';
	return {
		filePath: path.join(outputDir, 'auto-register.ts'),
		banner: [
			'/**',
			' * AUTO-GENERATED by WPKernel CLI.',
			` * Source: ${bannerSource} → blocks.jsOnly`,
			' */',
		],
		registrationFunction: 'registerGeneratedBlocks',
		settingsHelper: 'createGeneratedBlockSettings',
	};
}

/**
 * Normalises an absolute block path into a relative module specifier.
 *
 * @param    blockPath
 * @param    outputPath
 * @category Builders
 */
export function generateBlockImportPath(
	blockPath: string,
	outputPath: string
): string {
	const relativePath = path.relative(path.dirname(outputPath), blockPath);
	const normalised = relativePath.split(path.sep).join('/');

	if (!normalised.startsWith('.')) {
		return `./${normalised}`;
	}

	return normalised;
}
