<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.job
 * Schema: auto:job (auto)
 * Route: [GET] /test-namespace/v1/jobs
 */
namespace Test\Namespace\Generated\Rest;

use WP_Error;
use WP_Post;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
class JobController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'job';
    }
    public function get_schema_key(): string
    {
        return 'auto:job';
    }
    public function get_rest_args(): array
    {
        return ['department' => ['schema' => ['type' => 'string']], 'tags' => ['schema' => ['items' => ['type' => 'string'], 'type' => 'array']]];
    }
    /**
     * Register REST routes for this controller.
     * Capability enforcement happens inside each handler via Capability::enforce,
     * so permission_callback is intentionally __return_true here.
     */
    public function register_routes(): void
    {
        // permission_callback is __return_true; capabilities enforced inside handlers.
        register_rest_route('test-namespace/v1', '/jobs', [['methods' => 'GET', 'callback' => [$this, 'getV1Jobs'], 'permission_callback' => '__return_true']]);
    }
    /**
     * Handle [GET] /test-namespace/v1/jobs.
     * @wp-kernel route-kind custom
     */
    public function getV1Jobs(WP_REST_Request $request)
    {
        // TODO: Implement handler for [GET] /test-namespace/v1/jobs.
        // Reason: wp-post storage does not implement "custom" routes.
        // Hint: Supported route kinds are list, get, create, update, and remove.
        return new WP_Error(501, 'Not Implemented');
    }
    protected function getJobPostType(): string
    {
        return 'test_namespace_job';
    }
    protected function getJobStatuses(): array
    {
        return ['publish', 'draft'];
    }
    protected function normaliseJobStatus($status): string
    {
        $allowed = $this->getJobStatuses();
        $candidate = is_string($status) ? strtolower($status) : '';
        foreach ($allowed as $value) {
            if ($candidate === strtolower($value)) {
                return $value;
            }
        }
        $fallback = 'draft';
        if (!in_array('draft', $allowed, true)) {
            if (!empty($allowed)) {
                $fallback = $allowed[0];
            }
        }
        return $fallback;
    }
    protected function resolveJobPost($id)
    {
        $post_id = is_numeric($id) ? (int) $id : 0;
        if ($post_id <= 0) {
            return null;
        }
        $post = get_post($post_id);
        if (!$post instanceof WP_Post) {
            return null;
        }
        if ($post->post_type !== $this->getJobPostType()) {
            return null;
        }
        return $post;
    }
    private function syncJobMeta(int $post_id, WP_REST_Request $request): void
    {
        $departmentMeta = rest_sanitize_value_from_request('department', $request);
        if (null !== $departmentMeta) {
            $departmentMeta = is_string($departmentMeta) ? $departmentMeta : (string) $departmentMeta;
            update_post_meta($post_id, 'department', $departmentMeta);
        }
        $tagsMeta = rest_sanitize_value_from_request('tags', $request);
        if (null !== $tagsMeta) {
            $tagsMeta = is_string($tagsMeta) ? $tagsMeta : (string) $tagsMeta;
            delete_post_meta($post_id, 'tags');
            foreach ((array) $tagsMeta as $value) {
                add_post_meta($post_id, 'tags', $value);
            }
        }
    }
    function syncJobTaxonomies(int $post_id, WP_REST_Request $request)
    {
        unset($post_id, $request);
        return true;
    }
    function prepareJobResponse(WP_Post $post, WP_REST_Request $request): array
    {
        $data = ['id' => (int) $post->ID, 'status' => (string) $post->post_status];
        $departmentMeta = get_post_meta($post->ID, 'department', true);
        $data['department'] = $departmentMeta;
        $tagsMeta = get_post_meta($post->ID, 'tags', false);
        $data['tags'] = $tagsMeta;
        return $data;
    }
}
// WPK:END AUTO
