<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.second
 * Schema: auto:second (auto)
 * Route: [GET] https://api.example.com/items
 */
namespace Test\Namespace\Generated\Rest;

use WP_Error;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
class SecondController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'second';
    }
    public function get_schema_key(): string
    {
        return 'auto:second';
    }
    public function get_rest_args(): array
    {
        return [];
    }
    /**
     * Register REST routes for this controller.
     * Capability enforcement happens inside each handler via Capability::enforce,
     * so permission_callback is intentionally __return_true here.
     */
    public function register_routes(): void
    {
        // permission_callback is __return_true; capabilities enforced inside handlers.
        register_rest_route('https:/api.example.com', '/items', [['methods' => 'GET', 'callback' => [$this, 'getHttpsApiExampleComItems'], 'permission_callback' => '__return_true']]);
    }
    /**
     * Handle [GET] https://api.example.com/items.
     * @wp-kernel route-kind custom
     */
    public function getHttpsApiExampleComItems(WP_REST_Request $request)
    {
        // TODO: Implement handler for [GET] https://api.example.com/items.
        // Reason: Route transport is remote. CLI only generates local handlers.
        // Hint: Implement the remote route manually or switch it to local transport with supported storage.
        return new WP_Error(501, 'Not Implemented');
    }
}
// WPK:END AUTO
