<?php

declare(strict_types=1);
/**
 * AUTO-GENERATED by WPKernel CLI.
 * Edits between WPK:BEGIN AUTO and WPK:END AUTO will be overwritten.
 * Source: wpk.config.ts → resources.todo
 * Schema: todo (manual)
 * Route: [GET] /test-namespace/v1/items
 */
namespace Test\Namespace\Generated\Rest;

use WP_Error;
use WP_REST_Request;
use function is_wp_error;
// WPK:BEGIN AUTO
class TodoController extends BaseController
{
    public function get_resource_name(): string
    {
        return 'todo';
    }
    public function get_schema_key(): string
    {
        return 'todo';
    }
    public function get_rest_args(): array
    {
        return ['completed' => ['schema' => ['type' => 'boolean']], 'id' => ['required' => true, 'schema' => ['type' => 'integer']], 'title' => ['required' => true, 'schema' => ['type' => 'string']]];
    }
    /**
     * Register REST routes for this controller.
     * Capability enforcement happens inside each handler via Capability::enforce,
     * so permission_callback is intentionally __return_true here.
     */
    public function register_routes(): void
    {
        // permission_callback is __return_true; capabilities enforced inside handlers.
        register_rest_route('test-namespace/v1', '/items', [['methods' => 'GET', 'callback' => [$this, 'getV1Items'], 'permission_callback' => '__return_true']]);
    }
    /**
     * Handle [GET] /test-namespace/v1/items.
     * @wp-kernel route-kind custom
     */
    public function getV1Items(WP_REST_Request $request)
    {
        // TODO: Implement handler for [GET] /test-namespace/v1/items.
        // Reason: Resource has no storage configuration.
        // Hint: Add a storage mode to resources.todo or mark the route transport as "remote".
        return new WP_Error(501, 'Not Implemented');
    }
}
// WPK:END AUTO
